### ISSUE TITLE
Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by fernandoboiero** [GluuFederation/openid-implicit-client#14]
I've just deployed Gluu server and was trying to test this JS client but I'm getting the following error when calling the userinfo endpoint.

XMLHttpRequest cannot load https://aa01.mydomain.com/oxauth/seam/resource/restv1/oxauth/userinfo. Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by willow9886** [comment]
Hi there, can you please open this as an issue on our http://support.gluu.org site? 

We will be able to better track and assign the issue there. Also, please provide enough information for us to reproduce the error (screenshots, logs, etc..). 

Thanks,
Will
