### ISSUE TITLE
Setting the audience for the generated access_token

### ISSUE THREAD

**Issue by LorisBachert** [GluuFederation/openid-implicit-client#22]
Since the API does not support sending a request object to the authorization endpoint so far i'm trying to write this functionality on my own because we want to set the audience for the acces_token we are generating. I'm having a hard time with encrypting and signing the request object.

Is there any other way than passing the request object to set the audience?
If not, can you give me a hint how i should be able to encrypt/sign the jwt? Because as far as i understood i need a private key to encrypt my jwt. How do i get one and make the server understand it?

This is what i got so far:
```javascript
let jwks = this['jwks'] || this.fetchJSON(this['jwks_uri']);
if(!jwks)
	console.error('No JWK keyset');
else {
	let jwk = this.jwk_get_key(jwks, 'EC', 'sig', null);
	if (!jwk)
		console.error('No matching JWK found');
	let algorithm = "ES256";
	let jwkForAlgorithm = jwk.filter(alg => alg.alg === algorithm)[0];
	try {
		let KJUR = require('jsrsasign');
		let header = {alg: algorithm, typ: 'JWT'};
		let sHeader = JSON.stringify(header);
		let sPayload = JSON.stringify(requestObject);
		// get key by the jwk
		let key = KJUR.KEYUTIL.getKey(jwkForAlgorithm);
		// the key is only a public key
		let sJWT = KJUR.jws.JWS.sign(algorithm, sHeader, sPayload, key);
		debugger;
		return sJWT;
	} catch(e) {
		// signature is missing the private key
		debugger;
	}
}
```
which throws:
```
Signature: unsupported private key alg: ecdsa
```

Thank you,
Loris

**Comment by mzico** [comment]
@LorisBachert : Please use our support portal ( https://support.gluu.org ) for any kind of question and/or support. We are using github only for bug tracking.

**Comment by nynymike** [comment]
The audience is always your client_id.  I have also asked OpenID gurus how the OP would know to set multiple `aud` values. I don't think there are any standards there.  If the API is in the same administrative domain, one might argue that it's ok to consume an identity assertion from a trusted client.
