### ISSUE TITLE
Update jsrsasign

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/openid-implicit-client#4]
The jsjws is now merged into jsrsasign and any further update for jsjws will be done only in jsrsasign. See if we can replace the jsjws methods.

Also, if there are jsrsasign methods, they should be updated to the latest versions.

http://kjur.github.io/jsrsasign/

**Comment by toledorafael** [comment]
All done in #12. The verifyJWSByNE() method was replaced by verify().
